### ISSUE TITLE
KeyError: 'final_box_dicts' When I am running Centerpoint in demo.py

### ISSUE THREAD

**Issue by wangyakunn** [open-mmlab/OpenPCDet#1377]
Thanks a lot for such an excellent DP frame!
The centerpoint.yaml is:
```
CLASS_NAMES: ['Car']
DATA_CONFIG: 
    _BASE_CONFIG_: cfgs/dataset_configs/custom_dataset.yaml


MODEL:
    NAME: CenterPoint

    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5]
        LAYER_STRIDES: [1]
        NUM_FILTERS: [128]
        UPSAMPLE_STRIDES: [2]
        NUM_UPSAMPLE_FILTERS: [256]

    DENSE_HEAD:
        NAME: CenterHead
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: False 

        TARGET_ASSIGNER_CONFIG:
            MAX_OBJS: 100
            VOXEL_SIZE: [0.05, 0.05, 0.1]
            OUT_SIZE_FACTOR: 4 
            GAUSSIAN_OVERLAP: 0.1
            MIN_RADIUS: 2
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.01
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 8
    NUM_EPOCHS: 80

    OPTIMIZER: adam_onecycle
    LR: 0.003
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001


    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
```
When model.forward() ，it pass through MeanVFE,VoxelBackBone8x,HeightCompression,BaseBEVBackbone,CenterHead as the cfg is.But the final batch_dict.keys is [ 'points', 'frame_id', 'use_lead_xyz', 'voxels', 'voxel_coords', 'voxel_num_points', 'batch_size', 'voxel_features', 'encoded_spconv_tensor', 'encoded_spconv_tensor_stride', 'multi_scale_3d_features', 'multi_scale_3d_strides', 'spatial_features', 'spatial_features_stride', 'spatial_features_2d', 'batch_cls_preds', 'batch_box_preds', 'cls_preds_normalized']
There is no key 'final_box_dicts'. Why is this happening？
