### ISSUE TITLE
My custom dataset has a class that dose not exist in kitti 

### ISSUE THREAD

**Issue by yux326** [open-mmlab/OpenPCDet#1508]
I'm trying to train Pointpillar model with my own dataset whhich consists of three classes: Car, Bus, Truck.
I found in CUSTOM_DATASET_TUTORIAL.md that I have to map class names of my dataset to kitti class names, but there is no class in kitti  matches "Bus" in my dataset. How can I deal with this?

**Comment by tyutlk** [comment]
just match "bus" with "car"  and it just has effects on  the evaluation.

**Comment by yux326** [comment]
Thanks.
But I also have “Car" in my dataset, " there is also the class 'Car.' Will mapping 'bus' to 'car' cause confusion between these two classes?
Besides i wonder what to do while training?

**Comment by Petros626** [comment]
```yaml
MAP_CLASS_TO_KITTI: {
    'Vehicle': 'Car',
    'Pedestrian': 'Pedestrian',
    'Cyclist': 'Cyclist',
}
```
