### ISSUE TITLE
SCORE_THRESH in pointpillar.yaml

### ISSUE THREAD

**Issue by penghao1990** [open-mmlab/OpenPCDet#261]
Hi
Nice work. 

I want to konw how to set the SCORE_THRESH  in pointpillar.yaml, because the results corresponding to different SCORE_THRESH are not the same. When the SCORE_THRESH is set low, many redundant boxes will be predicted.

Dataset： Kitti.
```yaml
    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.01
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500

```

Thanks.
