### ISSUE TITLE
About argoverse dataset config

### ISSUE THREAD

**Issue by Shuntw6096** [open-mmlab/OpenPCDet#635]
Hi, I trained a point rcnn with kitti, and I want test on argoverse,  but get low AP on argoverse,
![Imgur](https://i.imgur.com/wGA6mhn.jpg)
I translate argoverse dataset to kitti format using [Train in Germany, Test in The USA: Making 3D Object Detectors Generalize](https://github.com/cxy1997/3D_adapt_auto_driving)'s code, it seems working, and check kitti format with [kitti_object_vis](https://github.com/kuixu/kitti_object_vis).
Argoverse:
![Imgur](https://i.imgur.com/HrH1J2f.png)
![Imgur](https://i.imgur.com/uomqOgA.png)
I think that some parameters settings are wrong because I use kitti's dataset setting, and I don't know how to set argoverse's `POINT_CLOUD_RANGE`, how to get  `POINT_CLOUD_RANGE` parameters?

argoverse datset setting below:

``` yaml
DATASET: 'ArgoDataset'
DATA_PATH: '../data/argo'

POINT_CLOUD_RANGE: [0, -40, -3, 200, 40, 1]

DATA_SPLIT: {
    'train': train,
    'test': val
}

INFO_PATH: {
    'train': [kitti_infos_train.pkl],
    'test': [kitti_infos_val.pkl],
}

GET_ITEM_LIST: ["points"]
FOV_POINTS_ONLY: True

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        - NAME: gt_sampling
          USE_ROAD_PLANE: False
          DB_INFO_PATH:
              - kitti_dbinfos_train.pkl
          PREPARE: {
             filter_by_min_points: ['Car:5', 'Pedestrian:5', 'Cyclist:5'],
             filter_by_difficulty: [-1],
          }

          SAMPLE_GROUPS: ['Car:20','Pedestrian:15', 'Cyclist:15']
          NUM_POINT_FEATURES: 4
          DATABASE_WITH_FAKELIDAR: False
          REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
          LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.95, 1.05]


POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}


DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.05, 0.05, 0.1]
      MAX_POINTS_PER_VOXEL: 5
      MAX_NUMBER_OF_VOXELS: {
        'train': 16000,
        'test': 40000
      }
```
I use [model setting](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/kitti_models/pointrcnn.yaml) but change ```CLASS_NAMES``` to ```['Car']```
Thanks.
