### ISSUE TITLE
I get a very low AP when I try to use multiple shared headers in CenterHead

### ISSUE THREAD

**Issue by weipingxiao** [open-mmlab/OpenPCDet#756]
- training details

  - model: pv_rcnn_plusplus_resnet.yaml

  - epoch: 6 (for fast validation)

  - dataset: ONCE

    ```
    DATA_CONFIG:
        _BASE_CONFIG_: cfgs/dataset_configs/once_dataset.yaml
        
    POST_PROCESSING:
            EVAL_METRIC: once
    ```

- results (format: mAP [vehicle AP, pedestrian AP, cyclist AP])

  - 54.44 [69.25, 37.8, 56.26]

    ```
    CLASS_NAMES_EACH_HEAD: [
    	['Car', 'Bus', 'Truck', 'Pedestrian', 'Cyclist']
    ]
    ```

  - 35.68 [68.96, 37.64, 0.43]

    ```
    CLASS_NAMES_EACH_HEAD: [
    	['Car', 'Bus', 'Truck', 'Pedestrian'],['Cyclist']
    ]
    ```

  - 24.73 [70.45, 3.52, 0.22]

    ```
    CLASS_NAMES_EACH_HEAD: [
    	['Car', 'Bus', 'Truck'], ['Pedestrian', 'Cyclist']
    ]
    ```

I only modified the above configuration. As you can see from the results, when I used two shared headers for different classes, the accuracy of one of the shared headers was poor. Can anyone tell me where I am going wrong? Thank you so much.
