### ISSUE TITLE
Question: How to perform inference from sensor_msgs/msg/PointCloud2 messages

### ISSUE THREAD

**Issue by tleyden** [open-mmlab/OpenPCDet#81]
I'm trying to perform inference with `sensor_msgs/msg/PointCloud2` messages with the following structure:

```
---
header:
  stamp:
    sec: 1591579194
    nanosec: 532001792
  frame_id: lidar_front
height: 1
width: 4314
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: intensity
  offset: 16
  datatype: 2
  count: 1
- name: timestamp
  offset: 24
  datatype: 8
  count: 1
is_bigendian: false
point_step: 32
row_step: 138048
data: [41, 80, 35, 65, 251, 212, 240, 183, 63, 95, 230, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 148, 252, 34, 65, 54, 27, 54, 190, 62, 242, 229, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 168, 34, 65, 194, 198, 181, 190, 142, 150, 229, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 226, 89, 34, 65, 144, 36, 8, 191, 80, 84, 229, 191, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '...']
is_dense: true
```

If I converted this into the same point cloud format that pcdet expects, would this be enough to perform inference and generate 3D bounding boxes?  Any examples or pointers?
